<?php

/**
 * Release details for the PSGC dataset in this directory.
 *
 * Generated by bin/build-psgc.php from PSGC-2Q-2026-Publication-Datafile.xlsx. Do not edit by hand.
 * See docs/updating-psgc.md to rebuild it from a new PSA release.
 */

declare(strict_types=1);

return [
    'release' => '2026-06-30',
    'source' => 'Philippine Statistics Authority, Philippine Standard Geographic Code (PSGC)',
    'sourceFile' => 'PSGC-2Q-2026-Publication-Datafile.xlsx',
    'counts' => [
        'regions' => 18,
        'provinces' => 84,
        'cities' => 1656,
        'barangays' => 42010,
    ],
];
